export const songs = [
    { name: 'Euphoria Symphony', artist: 'Luna Melodiosa', image: 'cds' },
    { name: 'Retro Grooves', artist: 'Neon Beats', image: 'vinil' },
    { name: 'Whispering Dreams', artist: 'Aurora Harmonics', image: 'cds' },
    { name: 'Jazz Noir', artist: 'Midnight Serenaders', image: 'tapes' },
    { name: 'Enchanted Melodies', artist: 'Celestial Sounds', image: 'cds' },
    { name: 'Electric Dreams', artist: 'Synthwave Explorers', image: 'tapes' },
    { name: 'Serenity Sonata', artist: 'Dusk Ensemble', image: 'cds' },
    { name: 'Urban Rhythms', artist: 'City Pulse', image: 'tapes' },
    { name: 'Mystic Overture', artist: 'Ethereal Ensemble', image: 'cds' },
    { name: 'Luminous Echoes', artist: 'Starry Resonance', image: 'tapes' },
    { name: 'Whimsical Waltz', artist: 'Carnival Orchestra', image: 'cds' },
    { name: 'Galactic Groove', artist: 'Cosmic Travelers', image: 'vinil' },
    { name: 'Silent Reverie', artist: 'Moonlit Reflections', image: 'cds' },
    { name: 'Neon Nocturne', artist: 'Synthetic Nightlife', image: 'tapes' },
    { name: 'Emerald Elegy', artist: 'Verdant Melodies', image: 'vinil' }
  ];

  export const songsTwo = [
    { name: 'Summer Breeze', artist: 'Sunset Serenaders', image: 'tapes' },
    { name: 'Moonlit Melodies', artist: 'Starry Nights Orchestra', image: 'cds' },
    { name: 'Dancing Raindrops', artist: 'Harmony Echoes', image: 'vinil' },
    { name: 'Jazz Café', artist: 'Midnight Ensemble', image: 'notes' },
    { name: 'Enchanted Forest', artist: 'Mystic Harmonies', image: 'tapes' },
    { name: 'Neon Lights', artist: 'Synthwave Seekers', image: 'cds' },
    { name: 'Serene Sunset', artist: 'Twilight Echoes', image: 'vinil' },
    { name: 'City Vibes', artist: 'Urban Pulse', image: 'notes' },
    { name: 'Crystal Whispers', artist: 'Celestial Harmony', image: 'tapes' },
    { name: 'Starlit Serenade', artist: 'Cosmic Melodies', image: 'cds' },
    { name: 'Carnival Fantasy', artist: 'Joyful Orchestras', image: 'notes' },
    { name: 'Galactic Adventure', artist: 'Interstellar Travelers', image: 'vinil' },
    { name: 'Midnight Reverie', artist: 'Lunar Reflections', image: 'tapes' },
    { name: 'Synthetic Dreams', artist: 'Electric Nocturnes', image: 'cds' },
    { name: 'Emerald Echoes', artist: 'Verdant Harmonics', image: 'notes' }
  ];
  
  export const songsThree = [
    { name: 'Midnight Serenade', artist: 'Luna Nightshade', image: 'cds' },
    { name: 'Echoes of Eternity', artist: 'Astral Harmonies', image: 'tapes' },
    { name: 'Dance of the Stars', artist: 'Celestial Dancers', image: 'notes' },
    { name: 'Urban Grooves', artist: 'City Beats', image: 'vinil' },
    { name: 'Dreamer\'s Lullaby', artist: 'Serene Dreamscapes', image: 'tapes' },
    { name: 'Neon Reflections', artist: 'Synthwave Explorers', image: 'cds' },
    { name: 'Enchanted Gardens', artist: 'Mystic Melodies', image: 'notes' },
    { name: 'Twilight Jazz', artist: 'Nightfall Quartet', image: 'vinil' },
    { name: 'Crystal Whispers', artist: 'Harmonic Resonance', image: 'cds' },
    { name: 'Starry Nocturne', artist: 'Celestial Echoes', image: 'tapes' },
    { name: 'Carnival Adventure', artist: 'Joyful Performers', image: 'vinil' },
    { name: 'Galactic Serenity', artist: 'Cosmic Symphony', image: 'notes' },
    { name: 'Moonlit Reverie', artist: 'Silvermoon Ensemble', image: 'tapes' },
    { name: 'Synthetic Dreams', artist: 'Electric Waves', image: 'cds' },
    { name: 'Emerald Harmony', artist: 'Verdant Serenades', image: 'vinil' }
  ];

  export const songsFour = [
    { name: 'Celestial Reverie', artist: 'Aurora Echoes', image: 'vinil' },
    { name: 'City Lights', artist: 'Urban Harmony', image: 'notes' },
    { name: 'Whispering Winds', artist: 'Mystic Melodics', image: 'cds' },
    { name: 'Jazzed Up', artist: 'Midnight Jazz Trio', image: 'tapes' },
    { name: 'Ethereal Dreams', artist: 'Dreamweavers', image: 'vinil' },
    { name: 'Synthetic Symphony', artist: 'Digital Serenades', image: 'notes' },
    { name: 'Serenity Falls', artist: 'Cascading Harmony', image: 'cds' },
    { name: 'Neon Nights', artist: 'Synthwave Sensation', image: 'tapes' },
    { name: 'Starlight Serenade', artist: 'Stellar Ensemble', image: 'cds' },
    { name: 'Enchanted Voyage', artist: 'Mystic Journeys', image: 'vinil' },
    { name: 'Carnival Rhythms', artist: 'Joyful Beats', image: 'notes' },
    { name: 'Galactic Melancholy', artist: 'Cosmic Echoes', image: 'cds' },
    { name: 'Moonlit Sonata', artist: 'Lunar Harmonics', image: 'tapes' },
    { name: 'Digital Dreams', artist: 'Electric Soundscapes', image: 'vinil' },
    { name: 'Emerald Twilight', artist: 'Verdant Nocturnes', image: 'notes' }
  ];
  
  export const secondarySongs = [
    { name: "Skyline Serenade", artist: "Aria Nova", image: "cds", alt: "cds de música" },
    { name: "Whispering Meadows", artist: "Eclipse Echo", image: "vinil", alt: "retrato de vinil" },
    { name: "Rhythm Reverie", artist: "Harmony Harmony", image: "notes", alt: "notas musicais" },
    { name: "Melody Mirage", artist: "Echo Ensemble", image: "tapes", alt: "fitas de música" },
    { name: "Mystic Groove", artist: "Solstice Sound", image: "cds", alt: "cds de música" },
    { name: "Enchanted Echoes", artist: "Luna Lyric", image: "vinil", alt: "retrato de vinil" },
    { name: "Harbor Harmony", artist: "Marina Melodies", image: "notes", alt: "notas musicais" },
    { name: "Serenade Sands", artist: "Horizon Hues", image: "tapes", alt: "fitas de música" },
    { name: "Twilight Tango", artist: "Nova Nocturne", image: "cds", alt: "cds de música" },
    { name: "Starlight Sonata", artist: "Celestial Cadence", image: "vinil", alt: "retrato de vinil" },
    { name: "Dreamland Duet", artist: "Aurora Anthem", image: "notes", alt: "notas musicais" },
    { name: "Melodic Mirage", artist: "Echo Empyrean", image: "tapes", alt: "fitas de música" },
    { name: "Sapphire Symphony", artist: "Azure Aria", image: "cds", alt: "cds de música" },
    { name: "Golden Gleam", artist: "Radiant Rhapsody", image: "vinil", alt: "retrato de vinil" },
    { name: "Whispering Willow", artist: "Sylvan Serenade", image: "notes", alt: "notas musicais" },
    { name: "Harmonic Horizon", artist: "Mystic Melody", image: "tapes", alt: "fitas de música" },
    { name: "Ethereal Echo", artist: "Cascading Chords", image: "cds", alt: "cds de música" },
    { name: "Luminous Lullaby", artist: "Dawn Duette", image: "vinil", alt: "retrato de vinil" },
    { name: "Moonlit Melodies", artist: "Nocturne Nexus", image: "notes", alt: "notas musicais" },
    { name: "Harmony Haven", artist: "Serene Sonata", image: "tapes", alt: "fitas de música" },
    { name: "Velvet Voices", artist: "Aether Aria", image: "cds", alt: "cds de música" },
    { name: "Celestial Cadence", artist: "Stellar Serenade", image: "vinil", alt: "retrato de vinil" },
    { name: "Dreamer's Delight", artist: "Echoing Elysium", image: "notes", alt: "notas musicais" },
    { name: "Melody Mirage", artist: "Sonic Skyline", image: "tapes", alt: "fitas de música" },
    { name: "Whispering Woods", artist: "Vesper Verse", image: "cds", alt: "cds de música" },
    { name: "Oceanic Overture", artist: "Cerulean Chords", image: "vinil", alt: "retrato de vinil" },
    { name: "Enchanted Embrace", artist: "Harmonic Hush", image: "notes", alt: "notas musicais" },
    { name: "Lullaby Lagoon", artist: "Serenity Strings", image: "tapes", alt: "fitas de música" },
    { name: "Moonbeam Melody", artist: "Lunar Lilt", image: "cds", alt: "cds de música" },
    { name: "Whimsical Waltz", artist: "Mystic Minuet", image: "vinil", alt: "retrato de vinil" },
    { name: "Cascade Concerto", artist: "Ripple Rhapsody", image: "notes", alt: "notas musicais" },
    { name: "Serenity Serenade", artist: "Ethereal Echo", image: "tapes", alt: "fitas de música" },
    { name: "Harbor Harmony", artist: "Aqua Aria", image: "cds", alt: "cds de música" },
    { name: "Dusk Duet", artist: "Twilight Tune", image: "vinil", alt: "retrato de vinil" },
    { name: "Mystic Melodies", artist: "Sonic Solstice", image: "notes", alt: "notas musicais" },
    { name: "Luminous Lagoon", artist: "Radiant Rhapsody", image: "tapes", alt: "fitas de música" },
    { name: "Crescent Chords", artist: "Lunar Lyric", image: "cds", alt: "cds de música" },
    { name: "Starlit Sonata", artist: "Celestial Cadence", image: "vinil", alt: "retrato de vinil" },
    { name: "Harmonic Horizon", artist: "Echoing Ether", image: "notes", alt: "notas musicais" },
    { name: "Mystic Mirage", artist: "Enchanted Echo", image: "tapes", alt: "fitas de música" }
  ];
  
  